### ISSUE TITLE
Operation performed twice

### ISSUE THREAD

**Issue by alexolog** [0xC0000054/pdn-content-aware-fill#3]
The tool performs the calculations and displays a preview.
Upon hitting "OK", the tool performs the calculation again, which can be time consuming on large images.

Wouldn't it be faster just to copy the bits?

**Comment by 0xC0000054** [comment]
You are right, the built-in Paint.NET effects do not invalidate the effect token when the user presses OK.
I will change that.

**Comment by 0xC0000054** [comment]
It looks like Paint.NET is calling `OnSetRenderInfo` after the dialog closes and then skipping the `Render` call.
For most plugins this would be fine (they only use it to setup the parameters for `Render`), this plugin performs its rendering in `OnSetRenderInfo` and copies the results in `Render`.

**Comment by alexolog** [comment]
Can this be worked around?

**Comment by 0xC0000054** [comment]
> Can this be worked around?

Yes, it will be available in the next release.

**Comment by alexolog** [comment]
That was quick!
