### ISSUE TITLE
Plugin can lock up Paint.net for a long period of time

### ISSUE THREAD

**Issue by Jivix-zz** [0xC0000054/pdn-content-aware-fill#5]
Sometimes it takes an unexpectedly long time to update UI with "rendering", causing user (me) to think they missed the Apply button, clicking the button twice often locks up the system for more than a minute, sometimes several minutes.

The cancel button does nothing when the plugin is locked up, the plugin will then close immediately when it unlocks which is not quite what the user desired.

This lockup also happens when changing settings too quickly when the 'render automatically' option is selected.

Perhaps a "kill" button, or change behavior of the Cancel button to interrupt an unintentionally long render process?

**Comment by 0xC0000054** [comment]
The Cancel button already tells the render process to stop, but the rendering code only periodically checks for cancellation.
I will investigate how to make the rendering cancellation faster.

**Comment by Jivix-zz** [comment]
It sounds like it'd be worth it, especially considering that it's usually good to try a large number of combinations when trying to fill in a large selection that the algorithm is having trouble solving.
